### ISSUE TITLE
Have you implemented zoom function with QwtPlotMagnifier in qml?

### ISSUE THREAD

**Issue by CrawlWu** [carlos22/qwtquick2#2]

**Comment by carlos22** [comment]
No i don't think so. This only shows that it is possible. There is no integration between qml and qwt (c++). I moved over to https://github.com/evonove/qnite as it fits better for my usage.

**Comment by CrawlWu** [comment]
Sorry, I may not express it properly.I just reference your code and pass `event` to `QwtPlot` in event hanlder func.And I add some code like this:
```
    (void)new QwtPlotMagnifier( m_qwtPlot->canvas() );

    (void) new QwtPlotPanner( m_qwtPlot->canvas() )
```;
Theoretically,it should be worked.I am at puzzle, do you the best rule of thumb?

**Comment by CrawlWu** [comment]
Thks,I found the solution.I can't do it without your inspiration.
```
        QCoreApplication::sendEvent(m_qwtPlot->canvas(), newEvent);
        replotAndUpdate();
```
